### ISSUE TITLE
[imo] Tokenにアルファベット絵文字を追加するのを提案します

### ISSUE THREAD

**Issue by mipsparc** [itsu-dev/emojin#3]
Just an ideaでPRでなくて恐縮です。

テキストのみプレーンテキストなのは寂しいので、こちらいかがでしょうか！
🅰 🅱 🅲 🅳 🅴 🅵 🅶 🅷 🅸 🅹 🅺 🅻 🅼 🅽 🅾 🅿 🆀 🆁 🆂 🆃 🆄 🆅 🆆 🆇 🆈 🆉
ご存知かもしれませんが、ほかにも斜体などアルファベットはUnicodeでたくさん規定されています。
https://www.compart.com/en/unicode/

面白いと思ったらよかったら実装していただいてもいいですし、
つまらないなと思ったらCloseしていただいても構いません。

**Comment by itsu-dev** [comment]
@mipsparc ご提案ありがとうございます！文字列も絵文字になったらさらに楽しくなりそうです！

ですが、emojin は現状、各 OS の絵文字キーボードで入力できる範囲の絵文字しか使わない方針にしています（でないとデバッグも大変なので...）。
また、文字列は 💬 で囲まれた範囲を一括で文字列トークンとして扱っているのですが、各文字も規定の絵文字でトークン化してしまうと、扱える文字の種類が減ってしまう・処理が複雑になってしまうなどの懸念があります。

以上の理由から、大変恐縮ですが今回のご提案の実装は見送り、issue はクローズとさせていただきたいと思います。
emojin は現在開発中で、新しい要素を今後も追加していきたいと思っています。機会がありましたらまた楽しいアイデアをご提案いただければと思います。

**Comment by mipsparc** [comment]
すみません、雑な提案にご丁寧に対応いただきありがとうございました！

また適した絵文字など見つけたら（ご迷惑でなければ）ご提案しますね！
面白いプロダクトを作っていただきありがとうございます！

**Comment by mipsparc** [comment]
break に 💔 使うのはどうでしょうか

**Comment by itsu-dev** [comment]
ご提案ありがとうございます！そもそも break 文がなかったですね...
せっかくなので 💔 使わせていただこうと思います！

別に issue 切り出しておきますね。
